name = "The Return of Financial Irresponsibility"
author = "Mason"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d111b119fb54ceff96a4c1ce0d4e0a4e8af46926ec658ede2cac971a6002707c"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
