name = "The Return of Financial Irresponsibility"
author = "Mason"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c306deda24befce170647d476fba8dfd854c97a74a0e6e6fcf1278ea36e3a463"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
