name = "The Return of Financial Irresponsibility"
author = "Mason"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "418a70fa35f0dce95e87471876fb468afe507041be27649587154dca8a2ee3e8"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
