name = "The Return of Financial Irresponsibility"
author = "Mason"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a22d8673fe49bf7fe990986b90d9968adcacbeed435f1cc0728571bbdc9495d5"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
