name = "The Return of Financial Irresponsibility"
author = "Mason"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "400421f78936c666e28551058c4fe859e4557f1c078c39f1d4af60f8ef4b7dd5"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
