name = "The Return of Financial Irresponsibility"
author = "Mason"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "811e1a1014db7c0fb5a75ae79fdbd40f350c7d779c2711eac8ce2a912b1317ec"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
