name = "The Return of Financial Irresponsibility"
author = "Mason"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b165ea4e1ca8dbb20e85d3768f2a97d3725e0f1291a790f363f69cae1b3a7b41"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
