name = "VS Addition"
filename = "vs_addition-1.20.1-forge-0.0.5c+bebd605ca6.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "879a9cc15a6472a46b2bddd36c1dfd2b8ccdb106"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 5593354
project-id = 1027757
