name = "VS Addition"
filename = "vs_addition-1.20.1-forge-0.0.4b.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "a9b81c6038bcdb73f75d1c09cdbb70f911e0a312"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 5508574
project-id = 1027757
