name = "VS Addition"
filename = "vs_addition-1.20.1-forge-0.0.3i.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "30c5ce9796742dc0069caa6681e6585a256762c8"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 5414379
project-id = 1027757
