name = "VS Addition"
filename = "vs_addition-1.20.1-forge-0.0.6e+93b9fab0d6.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "ee43a621e9ac313440f768226a7be7d95361c16e"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 5679777
project-id = 1027757
