name = "VS Addition"
filename = "vs_addition-1.20.1-forge-0.0.4e.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "ea43d5c3adde967c084730c61d5efe0adbc8138f"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 5529490
project-id = 1027757
